const number_dict: BodyPartConstant[][]= [
    //MOVE WORK CARRY
[WORK, WORK, CARRY, MOVE], // 300
[WORK, WORK, CARRY, MOVE, MOVE], // 350
[WORK, WORK, CARRY, MOVE, MOVE, MOVE], //400
[WORK, WORK, WORK, CARRY, MOVE, MOVE], //450
[WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE], //500
[WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE], //550
[WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], //600
[WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], //650
[WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE], // 700
[WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], //750 
[WORK, WORK, WORK, WORK, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE], // 800
];

var a: number = 60;
console.log(60/50); //1.2
console.log(Math.ceil(60/50)); // 2
console.log(Math.floor(60/50)); // 1


